### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by saeedseyfi** [powerbuoy/sleek-css#4]
Hi Ante,
What do you think about adding RTL support to SleekCSS?

I know three methods to handle it, please take a look and share your thoughts:
1. [Handle it using sass mixins](https://gist.github.com/saeedseyfi/4eb9f4634d5eb053da05375c59092da8)
   - pros: 
     1. Smaller output file in comparison to method `#2`
     2. You'll have a semantic sass because of using `rtl` and `ltr` mixins
   - cons:
     1. You can't support both `rtl` and `ltr` both in a single output file
2. [Handle it using `dir` attr of `html` tag](https://gist.github.com/saeedseyfi/368c339ecacc6d3d251d3ef13ffe2bc7)
   - pros:
     1. You don't need to compile your sass file twice (you can support `rtl` and `ltr` in a single file)
   - cons:
     1. Your output file might get heavy because of long `css` rules
3. [Handle it using `sass` vars](https://www.sitepoint.com/manage-rtl-css-sass-grunt/)
   - pros:
     1. Smaller output file in comparison to both above methods
   - cons:
     1. You can't support both `rtl` and `ltr` both in a single output file
     2. Your `sass` files are not very semantic like method `#1`

I can take over adding the RTL support to Sleek.
Please advise.

**Comment by saeedseyfi** [comment]
@powerbuoy

**Comment by powerbuoy** [comment]
I do like method number 2, and I've actually used it in the past (@cols used to have RTL support for example, as did certain other components like .icon (just a margin change I believe)) but I actually recently removed it because I felt the code got a little bloated and also because I didn't have full support (not every component worked in RTL as far as I can remember at least).

I think the best way to do this would be to simply do something like:

```
.a-component {
    default: styling;

    [dir=rtl] & {
        rtl: fixes;
    }
}
```

Which components have you identified that _don't_ work in RTL? A lot of them should be exactly the same regardless (like @card, .group, .heading etc etc). I guess a quick search for "left" and "right" in the code will give a hint as to where we'd need to add some `[dir=rtl] &` fixes.

**Comment by saeedseyfi** [comment]
@powerbuoy  I think it can be better to mix method number 1 and 2, like this:

```
@mixin ltr {
    [dir=ltr] & {
        @content;
    }
}

@mixin rtl {
    [dir=rtl] & {
        @content;
    }
}
```

It has one more advantage: the developer can override rtl and ltr mixins and handle it out of Sleek as they like.

**Comment by saeedseyfi** [comment]
@powerbuoy Let's conclude tonight, please advise ;)

**Comment by powerbuoy** [comment]
Could you start with a fork and then we'll take it from there. I have a lot of cleanup planned for this repo atm.

**Comment by saeedseyfi** [comment]
@powerbuoy please take a look #5

**Comment by saeedseyfi** [comment]
@powerbuoy please let me know if you don't like to add rtl support to sleek ;)

**Comment by powerbuoy** [comment]
@saeedseyfi Sorry I haven't gotten around to it yet.
